# cursor navigator
map = capslock j, left
map = capslock alt_left j, shift_left left
map = capslock l, right
map = capslock alt_left l, shift_left right
map = capslock i, up
map = capslock alt_left i, shift_left up
map = capslock k, down
map = capslock alt_left k, shift_left down
map = capslock u, home
map = capslock alt_left u, shift_left home
map = capslock o, end
map = capslock alt_left o, shift_left end
map = capslock h, ctrl_left left
map = capslock alt_left h, ctrl_left shift_left left
map = capslock ;, ctrl_left right
map = capslock alt_left ;, ctrl_left shift_left right

# ctrl-remaps for better accessibility
map = capslock w, ctrl_left w
map = capslock r, ctrl_left r

# copy-pase
map = capslock b, ctrl_left x
map = capslock n, ctrl_left c
map = capslock m, ctrl_left v

# others
map = capslock backspace, delete
