# Fluent hotkey configuration

modifiers = ctrl_left, alt_left, shift_left, ctrl_right, alt_right, shift_right, capslock

bind = capslock, j -> left
bind = alt_left, capslock, j -> shift_left, left
bind = capslock, k -> down
bind = alt_left, capslock, k -> shift_left, down
bind = capslock, l -> right
bind = alt_left, capslock, l -> shift_left, right
bind = capslock, i -> up
bind = alt_left, capslock, i -> shift_left, up
bind = capslock, u -> home
bind = alt_left, capslock, u -> shift_left, home
bind = capslock, o -> end
bind = alt_left, capslock, o -> shift_left, end
bind = capslock, h -> ctrl_left, left
bind = alt_left, capslock, h -> ctrl_left, shift_left, left
bind = capslock, ; -> ctrl_left, right
bind = alt_left, capslock, ; -> ctrl_left, shift_left, right
bind = capslock, w -> ctrl_left, w
bind = capslock, b -> ctrl_left, x
bind = capslock, n -> ctrl_left, c
bind = capslock, m -> ctrl_left, v
bind = capslock, backspace -> delete
bind = capslock, r -> ctrl_left, r