[package]
name = "fluent"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
input-event-codes = { workspace = true }
serde = { workspace = true }
serde_plain = { workspace = true }
pest = { workspace = true }
pest_derive = { workspace = true }
thiserror = { workspace = true }
fluent-ipc = { path = "../fluent-ipc" }
tokio = { workspace = true }

[dev-dependencies]
libc = { workspace = true }
