WHITESPACE = _{ " " | "\t" }
NEWLINE = _{ "\r\n" | "\n" }

file = { SOI ~ statement* ~ EOI }

statement = _{
    modifiers
  | bind
  | comment
  | NEWLINE
}

modifiers = {
    "modifiers" ~ "=" ~ NEWLINE* ~ list ~ NEWLINE?
}

bind = {
    "bind" ~ "=" ~ NEWLINE* ~ list ~ NEWLINE* ~ "->" ~ NEWLINE* ~ list ~ NEWLINE?
}

list = {
    identifier ~ ("," ~ NEWLINE* ~ identifier)*
}

identifier = @{
    (!("," | " " | "\t" | "\r" | "\n" | "#" | "->") ~ ANY)+
}

comment = {
    "#" ~ (!NEWLINE ~ ANY)*
}