name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: cargo test
      - name: Clean
        run: rm -rf target
      - name: Vendor dependencies
        run:
            mkdir .cargo
            cargo vendor --locked > .cargo/config.toml
      - uses: ksm2/archive-action@v1
        with:
          format: "tar.gz"
          name: fluent
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: fluent.tar.gz
