name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: cargo test
      - name: Package
        run: |
            rm -rf target
            mkdir .cargo
            cargo vendor --locked > .cargo/config.toml
            tar -czf fluent.tar.gz --exclude *.tar.gz .
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: fluent.tar.gz
