name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Test
        run: cargo test --release
      - name: Clean Workdir
        run: rm -rf target
      - name: Package
        uses: ksm2/archive-action@v1
        with:
          format: "tar.gz"
          name: fluent
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: fluent-${{github.ref_name}}.tar.gz
